abstract class JsonString{
  static final String mockdata = '''{
    "data": {
        "curPage": 1,
        "datas": [
            {
                "apkLink": "",
                "author": "guojun_fire",
                "chapterId": 93,
                "chapterName": "基础知识",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": true,
                "id": 8171,
                "link": "https://juejin.im/post/5c9c2c76f265da60c576fab1",
                "niceDate": "10小时前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553786962000,
                "superChapterId": 134,
                "superChapterName": "自定义控件",
                "tags": [
                    
                ],
                "title": "你需要了解下Android View的更新requestLayout与重绘invalidate",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "Kenber",
                "chapterId": 73,
                "chapterName": "面试相关",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": true,
                "id": 8170,
                "link": "https://mp.weixin.qq.com/s/MRLn5xIVvCbKfc-IgX6tcQ",
                "niceDate": "10小时前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553786829000,
                "superChapterId": 197,
                "superChapterName": "热门专题",
                "tags": [
                    
                ],
                "title": "ByteDance Android 高工面试记",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "拉丁吴",
                "chapterId": 252,
                "chapterName": "奇怪的Bug",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": true,
                "id": 8169,
                "link": "https://www.jianshu.com/p/e6b5e7261c25",
                "niceDate": "10小时前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553786513000,
                "superChapterId": 135,
                "superChapterName": "项目必备",
                "tags": [
                    
                ],
                "title": "&quot;Only fullscreen opaque activities can request orientation &quot;问题再分析",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "hackest",
                "chapterId": 73,
                "chapterName": "面试相关",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": true,
                "id": 8168,
                "link": "https://www.jianshu.com/p/ccbfd77c6a25",
                "niceDate": "10小时前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553786275000,
                "superChapterId": 197,
                "superChapterName": "热门专题",
                "tags": [
                    
                ],
                "title": "Android曲折的求职之路(已经结束)",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "西瓜皮TWO ",
                "chapterId": 70,
                "chapterName": "retrofit",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8166,
                "link": "https://www.jianshu.com/p/8fcd545cb243",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698897000,
                "superChapterId": 98,
                "superChapterName": "网络访问",
                "tags": [
                    
                ],
                "title": "Retrofit开发踩的巨坑！",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": " zyl06",
                "chapterId": 185,
                "chapterName": "组件化",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8165,
                "link": "https://www.jianshu.com/p/a503db59c6eb",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698876000,
                "superChapterId": 197,
                "superChapterName": "热门专题",
                "tags": [
                    
                ],
                "title": "严选 Android 组件化实践",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "24K纯帅豆",
                "chapterId": 26,
                "chapterName": "基础UI控件",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8164,
                "link": "https://www.jianshu.com/p/e98eb28c6c6e",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698788000,
                "superChapterId": 26,
                "superChapterName": "常用控件",
                "tags": [
                    
                ],
                "title": "带着问题去看源码&mdash;&mdash;TextView篇",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "coder_yu",
                "chapterId": 198,
                "chapterName": "基础概念",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8163,
                "link": "https://www.jianshu.com/p/3afa47e9112e",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698757000,
                "superChapterId": 168,
                "superChapterName": "基础知识",
                "tags": [
                    
                ],
                "title": "Android类加载机制的细枝末节",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": " 文淑",
                "chapterId": 99,
                "chapterName": "具体案例",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8162,
                "link": "https://juejin.im/post/5c9aece86fb9a070b153f64b",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698719000,
                "superChapterId": 134,
                "superChapterName": "自定义控件",
                "tags": [
                    
                ],
                "title": "Android实现网页动态背景&ldquo;五彩蛛网&rdquo;",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "我没有三颗心脏",
                "chapterId": 73,
                "chapterName": "面试相关",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8161,
                "link": "https://www.jianshu.com/p/3f0cd7af370d",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553698701000,
                "superChapterId": 197,
                "superChapterName": "热门专题",
                "tags": [
                    
                ],
                "title": "【面试必备】手撕代码，你怕不怕？",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "逐梦々少年",
                "chapterId": 375,
                "chapterName": "Flutter",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8157,
                "link": "https://www.jianshu.com/p/9e31a9196981",
                "niceDate": "1天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553683275000,
                "superChapterId": 375,
                "superChapterName": "跨平台",
                "tags": [
                    
                ],
                "title": "flutter入门之dart中的类操作详解",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "Jensen95",
                "chapterId": 435,
                "chapterName": "小程序",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8156,
                "link": "https://www.jianshu.com/p/fd9ea1b57f8d",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616539000,
                "superChapterId": 375,
                "superChapterName": "跨平台",
                "tags": [
                    
                ],
                "title": "微信，支付宝小程序实现原理概述",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "Tikitoo",
                "chapterId": 296,
                "chapterName": "阅读",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8155,
                "link": "https://www.jianshu.com/p/18e3a28f757c",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616438000,
                "superChapterId": 181,
                "superChapterName": "延伸技术",
                "tags": [
                    
                ],
                "title": "技术类博客网站推荐",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "被代码淹没的小伙子",
                "chapterId": 54,
                "chapterName": "新的控件",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8154,
                "link": "https://www.jianshu.com/p/e44961f8add5",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616237000,
                "superChapterId": 54,
                "superChapterName": "5.+高新技术",
                "tags": [
                    
                ],
                "title": "【进阶】RecyclerView源码解析(二)&mdash;&mdash;缓存机制",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": " 被代码淹没的小伙子",
                "chapterId": 54,
                "chapterName": "新的控件",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8153,
                "link": "https://www.jianshu.com/p/c52b947fe064",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616207000,
                "superChapterId": 54,
                "superChapterName": "5.+高新技术",
                "tags": [
                    
                ],
                "title": "【进阶】RecyclerView源码解析(一)&mdash;&mdash;绘制流程",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "被代码淹没的小伙子",
                "chapterId": 198,
                "chapterName": "基础概念",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8152,
                "link": "https://www.jianshu.com/p/405a745aa4d0",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616177000,
                "superChapterId": 168,
                "superChapterName": "基础知识",
                "tags": [
                    
                ],
                "title": "一次奇葩问题导致的彻底了解View.post()的底层原理",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "hackest",
                "chapterId": 73,
                "chapterName": "面试相关",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8151,
                "link": "https://www.jianshu.com/p/57ba1ed23c49?",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616058000,
                "superChapterId": 197,
                "superChapterName": "热门专题",
                "tags": [
                    
                ],
                "title": "2018年年底Android悲催的面试之路",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "玉刚说",
                "chapterId": 410,
                "chapterName": "玉刚说",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8158,
                "link": "https://mp.weixin.qq.com/s/NHY5lqyNnxi7lS_4CQcrpw",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553616000000,
                "superChapterId": 408,
                "superChapterName": "公众号",
                "tags": [
                    {
                        "name": "公众号",
                        "url": "/wxarticle/list/410/1"
                    }
                ],
                "title": "不会搭建知识框架，活该你成不了技术大牛！",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": "承香墨影",
                "chapterId": 69,
                "chapterName": "okhttp",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8150,
                "link": "https://www.jianshu.com/p/940be2e758ee",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553615862000,
                "superChapterId": 98,
                "superChapterName": "网络访问",
                "tags": [
                    
                ],
                "title": "Android 网络优化，使用 HTTPDNS 优化 DNS，从原理到 OkHttp 集成",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            },
            {
                "apkLink": "",
                "author": " lalala同学",
                "chapterId": 228,
                "chapterName": "辅助 or 工具类",
                "collect": false,
                "courseId": 13,
                "desc": "",
                "envelopePic": "",
                "fresh": false,
                "id": 8149,
                "link": "https://juejin.im/post/5c961f585188252da05f4b08",
                "niceDate": "2天前",
                "origin": "",
                "projectLink": "",
                "publishTime": 1553615802000,
                "superChapterId": 135,
                "superChapterName": "项目必备",
                "tags": [
                    
                ],
                "title": "Android通用业务弹窗管理方案PopLayerV3- 业务流程控制",
                "type": 0,
                "userId": -1,
                "visible": 1,
                "zan": 0
            }
        ],
        "offset": 0,
        "over": false,
        "pageCount": 314,
        "size": 20,
        "total": 6265
    },
    "errorCode": 0,
    "errorMsg": ""
}''';
}